export const TAG_HIERARCHY = [
    {
        label: "H&H Modeling",
        children: [
            "Hydraulics",
            "Hydrology",
            "Water Distribution",
            "Sanitary Sewer",
            "Stormwater",
            "InfoWater",
            "InfoWater Pro",
            "WaterCAD",
            "Bentley FlowMaster",
            "HEC-RAS",
            "HEC-HMS",
            "HydroCAD",
            "River 2D",
            "SWMM",
            "InfoSWMM",
            "EPASWMM",
            "PC-SWMM",
            "SSOAP",
            "Calibration",
            "Flow Monitoring",
            "Hydrant Testing",
            "LTS",
            "Roughness Calibration",
            "CSO",
            "Pump Station",
            "Flumes",
            "Hydraflow",
            "InfoWorks ICM SE",
            "LOS",
            "Model Review",
            "Optimization",
            "Rate Setting",
            "RDII",
            "Regulator Investigation",
            "SSO",
            "Vectrino"
        ]
    },
    {
        label: "Design",
        children: [
            "CAD",
            "AutoCAD",
            "Civil 3D",
            "Bioretention",
            "E&S",
            "NPDES",
            "PCSM",
            "Permitting",
            "Site Design",
            "Augment",
            "Gates/Controls",
            "Geomagic",
            "Green Infrastructure",
            "Infraworks",
            "Interceptors",
            "Land Development",
            "Meshlab",
            "Pumps/Storage",
            "Sewer Separation",
            "SketchUp",
            "Spillway/Dam",
            "Storage Tanks",
            "TecPlot",
            "Trunkline Corridors",
            "Visualization",
            "Wincan"
        ]
    },
    {
        label: "GIS",
        children: [
            "ArcGIS",
            "ArcGIS Pro",
            "ArcGIS Online",
            "ArcGIS Dashboards",
            "ArcGIS Collector",
            "ArcGIS Field Maps",
            "ArcGIS Story Maps",
            "Web GIS",
            "Survey123",
            "ArcPad",
            "QGIS",
            "MapWindow",
            "GNSS",
            "GPS",
            "Trimble R2",
            "Quick Capture",
            "LiDAR",
            "Drone",
            "ArcGIS Desktop",
            "ArcMap",
            "Data Migration",
            "Domains",
            "Field Maps",
            "GIS Content",
            "GIS Migration",
            "InfoAsset Manager",
            "Laser Depth Gauge",
            "Leak Detection System",
            "Parcel Data",
            "Raster",
            "Schema",
            "TerraFlex",
            "Trimble TDC150",
            "Utility Schema",
            "Vector",
            "Watershed Delineation",
            "Web Apps",
            "Web Mapping"
        ]
    },
    {
        label: "Coding & Tools",
        children: [
            "Python",
            "Javascript",
            "VBA",
            "Excel",
            "Tool Development",
            "Automation",
            "AI",
            "Dashboard",
            "Data Science",
            "Analytics",
            "Power BI",
            "Node-RED",
            "SQL",
            "UI/UX",
            "Cloud Workflows",
            "IoT",
            "React",
            "Product Roadmap",
            "Batch Processing",
            "C++",
            "Data Consolidation",
            "Data Ingestion",
            "GA",
            "HTML",
            "Reinforcement Learning",
            "RMSE"
        ]
    },
    {
        label: "Project Management",
        children: [
            "Digital Delivery",
            "QA/QC",
            "Grant Application",
            "Master Plan",
            "SOP",
            "Staff Training",
            "Documentation",
            "Client Portals",
            "Google Drive",
            "Google Forms",
            "Google Sites",
            "Grants",
            "M365",
            "Microsoft Project",
            "PaDEP",
            "QA",
            "SharePoint"
        ]
    },
    {
        label: "Planning",
        children: [
            "Alternatives Analysis",
            "LTCP",
            "Master Planning",
            "Resiliency"
        ]
    },
];

