/**
 * Tiles marked `draft: true` are machine-generated by the GSD export and are
 * not finished: no category, tags, or image yet. They render in `npm run dev`
 * so they can be reviewed as real tiles, and are stripped from production
 * builds so a draft sitting in `main` never reaches the public site.
 */
export function visibleProjects(projects) {
  if (!import.meta.env.PROD) return projects;
  return projects.filter((p) => !p.draft);
}
