// Branching river networks on the lattice.
//
// Each network is a trunk with tributaries joining it, the way a real drainage
// system works — the molten runs as a network for the same reason the water
// does. Tributaries are generated by walking *away* from a point on the trunk
// and then reversing the result, which is what makes them genuinely join rather
// than merely end nearby.
//
// Routing is seeded, so a layout is reproducible and every reseed is a real
// alternative rather than a reshuffle of the same shape.

import { DIRS, DOWNSTREAM } from './lattice';

// Deterministic PRNG. Math.random would give a different world on every mount,
// including after a theme flip, which rebuilds the whole scene.
const mulberry = (a) => () => {
    a |= 0;
    a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};

const key = (x, y) => `${x},${y}`;

// One network per this many cells of field depth. Trunks are spread down the
// band rather than all entering at the top: starting them together meant they
// crowded each other out in the first screenful and the page below ran dry.
const CELLS_PER_NETWORK = 30;

export function buildNetworks(lattice, seed) {
    const rnd = mulberry(seed);
    // `halo` is every cell within one of an already-placed channel, which is
    // what holds channels apart. A channel's own trail is matched exactly
    // instead — a halo around itself would block the cell it just came from.
    const halo = new Set();
    let mine = new Set();

    const free = (x, y) =>
        lattice.inField(x, y) && !halo.has(key(x, y)) && !mine.has(key(x, y));

    const retire = () => {
        for (const k of mine) {
            const [mx, my] = k.split(',').map(Number);
            for (let dx = -1; dx <= 1; dx += 1) {
                for (let dy = -1; dy <= 1; dy += 1) halo.add(key(mx + dx, my + dy));
            }
        }
        mine = new Set();
    };

    // One walk. `flow` is +1 for a trunk heading downstream and -1 for a
    // tributary being traced back upstream from its confluence.
    function walk(startX, startY, startDir, flow, legs, turns) {
        let x = startX;
        let y = startY;
        let d = startDir;
        const pts = [[x, y]];
        mine.add(key(x, y));

        for (let leg = 0; leg < legs; leg += 1) {
            const run = 3 + Math.floor(rnd() * 7);
            let ranOff = false;
            for (let s = 0; s < run; s += 1) {
                const nx = x + DIRS[d][0];
                const ny = y + DIRS[d][1];
                if (!lattice.inField(nx, ny)) {
                    // Leaving the field is a clean way to end: the river runs
                    // off the edge of the world rather than stopping dead.
                    pts.push([nx, ny]);
                    ranOff = true;
                    break;
                }
                if (!free(nx, ny)) break;
                x = nx;
                y = ny;
                pts.push([x, y]);
                mine.add(key(x, y));
            }
            if (ranOff) break;

            const options = turns.slice().sort(() => rnd() - 0.5);
            let turned = false;
            for (const t of options) {
                const nd = (d + t + 8) % 8;
                if (DOWNSTREAM[nd] * flow < 0) continue;   // never reverse the flow
                if (free(x + DIRS[nd][0], y + DIRS[nd][1])) { d = nd; turned = true; break; }
            }
            // Boxed in: take any direction that still makes progress before
            // giving up. Ending the moment the preferred turns are blocked is
            // what leaves rivers as stubs.
            if (!turned) {
                for (let nd = 0; nd < 8; nd += 1) {
                    if (DOWNSTREAM[nd] * flow <= 0) continue;
                    if (free(x + DIRS[nd][0], y + DIRS[nd][1])) { d = nd; turned = true; break; }
                }
            }
            if (!turned) break;
        }
        return pts;
    }

    const channels = [];
    const depth = lattice.depth();
    const count = Math.max(2, Math.round(depth / CELLS_PER_NETWORK));

    for (let n = 0; n < count; n += 1) {
        // Every third network runs molten, so iron is a recurring thread down the
        // page rather than a single feature at the top.
        const kind = n % 3 === 1 ? 'molten' : 'water';
        const branches = kind === 'molten' ? 2 : 3;

        // Spread the entry points down the band, and stagger them across it.
        const across = Math.round((rnd() * 2 - 1) * lattice.halfWidth() * 0.72);
        const startV = Math.round(((n + 0.3 + rnd() * 0.4) / count) * depth * 0.94);
        const gx = Math.round((startV + across) / 2);
        const gy = startV - gx;
        if (!lattice.inField(gx, gy)) continue;
        const trunkDir = [0, 1, 2][Math.floor(rnd() * 3)];
        const trunk = walk(gx, gy, trunkDir, 1, 120, [1, -1, 2, -2]);
        if (trunk.length < 6) { retire(); continue; }
        channels.push({ kind, order: 1, pts: trunk });
        retire();

        // Tributaries: start on the trunk and trace back upstream, then reverse
        // so the geometry flows into the confluence.
        for (let b = 0; b < branches; b += 1) {
            const at = Math.floor((0.18 + 0.68 * ((b + rnd() * 0.6) / Math.max(1, branches))) * (trunk.length - 2)) + 1;
            const [jx, jy] = trunk[Math.min(trunk.length - 2, Math.max(1, at))];
            // Step clear of the trunk first, or the walk starts inside its halo.
            let seededDir = -1;
            for (let tries = 0; tries < 8; tries += 1) {
                const nd = Math.floor(rnd() * 8);
                if (DOWNSTREAM[nd] > 0) continue;
                if (free(jx + DIRS[nd][0], jy + DIRS[nd][1])) { seededDir = nd; break; }
            }
            if (seededDir < 0) continue;
            const upstream = walk(
                jx + DIRS[seededDir][0], jy + DIRS[seededDir][1],
                seededDir, -1, 40, [1, -1, 2, -2],
            );
            retire();
            if (upstream.length < 4) continue;
            // Reverse, and finish on the trunk so the join is exact.
            channels.push({ kind, order: 2, pts: [...upstream].reverse().concat([[jx, jy]]) });
        }
    }

    return channels;
}
